language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "amitnema-github"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar